terraform {
  required_version = ">= 1.4.0" # Required for terraform_data support

  required_providers {
    # Local provider manages the kubeconfig file generation
    local = {
      source  = "hashicorp/local"
      version = "~> 2.8.0"
    }

    helm = {
      source  = "hashicorp/helm"
      version = "3.1.1"
    }
  }
}

provider "helm" {
  kubernetes = {
    # Use the kubeconfig file generated by the terraform_data resource
    config_path = local_file.kubeconfig.filename
  }
}